import '../models/product_model.dart';
import '../models/category_model.dart';
import '../models/seller_model.dart';

class MockDataService {
  static List<SellerModel> getSellers() {
    return [
      SellerModel(
        id: 's1',
        name: 'Tiny Chicken Official',
        avatar: '🐔',
        banner:
            'https://picsum.photos/seed/5424/600/800',
        description:
            'Official Tiny Chicken store. Quality fashion for everyone.',
        rating: 4.9,
        productCount: 25,
        followerCount: 12500,
        isOfficial: true,
      ),
      SellerModel(
        id: 's2',
        name: 'Urban Streetwear',
        avatar: '🧢',
        banner:
            'https://picsum.photos/seed/5915/600/800',
        description: 'Street style that speaks volumes.',
        rating: 4.7,
        productCount: 8,
        followerCount: 8200,
      ),
      SellerModel(
        id: 's3',
        name: 'TechGear Hub',
        avatar: '🎧',
        banner:
            'https://picsum.photos/seed/1013/600/800',
        description: 'Premium electronics & gadgets.',
        rating: 4.8,
        productCount: 12,
        followerCount: 15300,
        isOfficial: true,
      ),
      SellerModel(
        id: 's4',
        name: 'HomeStyle Living',
        avatar: '🏠',
        banner:
            'https://picsum.photos/seed/7903/600/800',
        description: 'Beautiful things for your home.',
        rating: 4.6,
        productCount: 10,
        followerCount: 6700,
      ),
      SellerModel(
        id: 's5',
        name: 'BeautyGlow',
        avatar: '✨',
        banner:
            'https://picsum.photos/seed/4745/600/800',
        description: 'Skincare & beauty essentials.',
        rating: 4.8,
        productCount: 15,
        followerCount: 9800,
        isOfficial: true,
      ),
      SellerModel(
        id: 's6',
        name: 'SportFlex',
        avatar: '⚽',
        banner:
            'https://picsum.photos/seed/2831/600/800',
        description: 'Gear up for greatness.',
        rating: 4.5,
        productCount: 6,
        followerCount: 4500,
      ),
    ];
  }

  static SellerModel? getSellerById(String id) {
    try {
      return getSellers().firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<CategoryModel> getCategories() {
    return [
      CategoryModel(id: 'cat0', name: 'All', icon: '🏷️'),
      CategoryModel(id: 'cat1', name: 'Fashion', icon: '👕'),
      CategoryModel(id: 'cat2', name: 'Electronics', icon: '📱'),
      CategoryModel(id: 'cat3', name: 'Home & Living', icon: '🏠'),
      CategoryModel(id: 'cat4', name: 'Beauty', icon: '💄'),
      CategoryModel(id: 'cat5', name: 'Sports', icon: '⚽'),
      CategoryModel(id: 'cat6', name: 'Books', icon: '📚'),
      CategoryModel(id: 'cat7', name: 'Food & Drinks', icon: '🍕'),
      CategoryModel(id: 'cat8', name: 'Toys & Games', icon: '🎮'),
      CategoryModel(id: 'cat9', name: 'Automotive', icon: '🚗'),
      CategoryModel(id: 'cat10', name: 'Pets', icon: '🐾'),
    ];
  }

  static List<ProductModel> getProducts() {
    return [
      // ── FASHION ──
      ProductModel(
        id: 'p1',
        name: 'Vintage Chicken Graphic Tee',
        description:
            'Super soft vintage-inspired graphic tee featuring our iconic Tiny Chicken mascot. 100% organic cotton, relaxed fit.',
        price: 24.99,
        originalPrice: 39.99,
        images: [
          'https://picsum.photos/seed/275/600/800',
          'https://picsum.photos/seed/4232/600/800',
        ],
        category: 'Fashion',
        rating: 4.8,
        reviewCount: 234,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['White', 'Black'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 1520,
        isFlashSale: true,
        flashSalePrice: 14.99,
      ),
      ProductModel(
        id: 'p2',
        name: 'Floral Summer Dress',
        description:
            'Beautiful A-line floral dress with smocked back and adjustable straps.',
        price: 45.00,
        originalPrice: 65.00,
        images: [
          'https://picsum.photos/seed/9927/600/800',
        ],
        category: 'Fashion',
        rating: 4.6,
        reviewCount: 189,
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Pink', 'Blue'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 890,
      ),
      ProductModel(
        id: 'p3',
        name: 'Classic White Sneakers',
        description: 'Minimalist vegan leather sneakers with cushioned insole.',
        price: 59.99,
        originalPrice: 79.99,
        images: [
          'https://picsum.photos/seed/6775/600/800',
          'https://picsum.photos/seed/5264/600/800',
        ],
        category: 'Fashion',
        rating: 4.7,
        reviewCount: 412,
        sizes: ['6', '7', '8', '9', '10'],
        colors: ['White', 'Black'],
        sellerId: 's2',
        sellerName: 'Urban Streetwear',
        sellerAvatar: '🧢',
        soldCount: 2100,
        isFlashSale: true,
        flashSalePrice: 39.99,
      ),
      ProductModel(
        id: 'p4',
        name: 'Mini Crossbody Bag',
        description: 'Chic genuine leather crossbody with gold hardware.',
        price: 34.99,
        images: [
          'https://picsum.photos/seed/5905/600/800',
        ],
        category: 'Fashion',
        rating: 4.5,
        reviewCount: 156,
        colors: ['Tan', 'Black'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 670,
      ),
      ProductModel(
        id: 'p5',
        name: 'Slim Fit Chino Pants',
        description: 'Modern stretch cotton twill chinos, mid-rise, slim leg.',
        price: 42.00,
        originalPrice: 55.00,
        images: [
          'https://picsum.photos/seed/9498/600/800',
        ],
        category: 'Fashion',
        rating: 4.4,
        reviewCount: 98,
        sizes: ['28', '30', '32', '34'],
        colors: ['Khaki', 'Navy'],
        sellerId: 's2',
        sellerName: 'Urban Streetwear',
        sellerAvatar: '🧢',
        soldCount: 340,
      ),
      ProductModel(
        id: 'p6',
        name: 'Oversized Denim Jacket',
        description: 'Vintage-wash oversized denim jacket with button closure.',
        price: 68.00,
        originalPrice: 89.99,
        images: [
          'https://picsum.photos/seed/3713/600/800',
        ],
        category: 'Fashion',
        rating: 4.9,
        reviewCount: 321,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Light', 'Dark'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 1100,
        isFlashSale: true,
        flashSalePrice: 45.99,
      ),
      ProductModel(
        id: 'p7',
        name: 'Chunky Knit Beanie',
        description: 'Cozy acrylic blend beanie with logo patch.',
        price: 18.99,
        images: [
          'https://picsum.photos/seed/7846/600/800',
        ],
        category: 'Fashion',
        rating: 4.3,
        reviewCount: 67,
        colors: ['Cream', 'Charcoal'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 430,
      ),
      ProductModel(
        id: 'p8',
        name: 'Linen Blend Blazer',
        description: 'Lightweight unstructured blazer, notch lapels.',
        price: 79.99,
        originalPrice: 110.00,
        images: [
          'https://picsum.photos/seed/2480/600/800',
        ],
        category: 'Fashion',
        rating: 4.7,
        reviewCount: 145,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Beige', 'Grey'],
        sellerId: 's2',
        sellerName: 'Urban Streetwear',
        sellerAvatar: '🧢',
        soldCount: 280,
      ),
      ProductModel(
        id: 'p9',
        name: 'Striped Cotton Polo',
        description: 'Classic striped polo in pique cotton. Breathable.',
        price: 32.99,
        originalPrice: 45.00,
        images: [
          'https://picsum.photos/seed/5671/600/800',
        ],
        category: 'Fashion',
        rating: 4.4,
        reviewCount: 88,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Blue', 'Green'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 560,
      ),
      ProductModel(
        id: 'p10',
        name: 'Leather Ankle Boots',
        description: 'Handcrafted leather ankle boots with side zip.',
        price: 89.99,
        originalPrice: 120.00,
        images: [
          'https://picsum.photos/seed/5504/600/800',
        ],
        category: 'Fashion',
        rating: 4.6,
        reviewCount: 203,
        sizes: ['6', '7', '8', '9', '10'],
        colors: ['Brown', 'Black'],
        sellerId: 's2',
        sellerName: 'Urban Streetwear',
        sellerAvatar: '🧢',
        soldCount: 720,
      ),

      // ── ELECTRONICS ──
      ProductModel(
        id: 'p11',
        name: 'Wireless Earbuds Pro',
        description:
            'Active noise cancellation, 30hr battery, IPX5 waterproof.',
        price: 79.99,
        originalPrice: 129.99,
        images: [
          'https://picsum.photos/seed/9592/600/800',
        ],
        category: 'Electronics',
        rating: 4.7,
        reviewCount: 567,
        colors: ['Black', 'White'],
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 3400,
        isFlashSale: true,
        flashSalePrice: 49.99,
      ),
      ProductModel(
        id: 'p12',
        name: 'Smart Watch Series 5',
        description: 'AMOLED display, heart rate, GPS, 14-day battery.',
        price: 199.99,
        originalPrice: 299.99,
        images: [
          'https://picsum.photos/seed/9135/600/800',
        ],
        category: 'Electronics',
        rating: 4.8,
        reviewCount: 890,
        colors: ['Silver', 'Black', 'Rose Gold'],
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 5600,
      ),
      ProductModel(
        id: 'p13',
        name: 'Portable Bluetooth Speaker',
        description: '360° sound, 20hr playtime, waterproof IPX7.',
        price: 49.99,
        originalPrice: 69.99,
        images: [
          'https://picsum.photos/seed/6586/600/800',
        ],
        category: 'Electronics',
        rating: 4.5,
        reviewCount: 345,
        colors: ['Blue', 'Red', 'Black'],
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 2100,
      ),
      ProductModel(
        id: 'p14',
        name: 'USB-C Hub 7-in-1',
        description: 'HDMI 4K, SD/TF, USB 3.0 x3, PD 100W.',
        price: 34.99,
        images: [
          'https://picsum.photos/seed/5456/600/800',
        ],
        category: 'Electronics',
        rating: 4.4,
        reviewCount: 178,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 890,
      ),
      ProductModel(
        id: 'p15',
        name: 'Mechanical Keyboard RGB',
        description: 'Cherry MX Blue switches, per-key RGB, aluminum frame.',
        price: 89.99,
        originalPrice: 119.99,
        images: [
          'https://picsum.photos/seed/9826/600/800',
        ],
        category: 'Electronics',
        rating: 4.6,
        reviewCount: 234,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 1200,
      ),
      ProductModel(
        id: 'p16',
        name: '4K Webcam Pro',
        description: 'Auto-focus, built-in ring light, noise-canceling mic.',
        price: 69.99,
        images: [
          'https://picsum.photos/seed/290/600/800',
        ],
        category: 'Electronics',
        rating: 4.3,
        reviewCount: 156,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 670,
      ),
      ProductModel(
        id: 'p17',
        name: 'Wireless Charging Pad',
        description: '15W fast charge, compatible with all Qi devices.',
        price: 19.99,
        originalPrice: 29.99,
        images: [
          'https://picsum.photos/seed/6255/600/800',
        ],
        category: 'Electronics',
        rating: 4.2,
        reviewCount: 432,
        colors: ['Black', 'White'],
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 2800,
      ),

      // ── HOME & LIVING ──
      ProductModel(
        id: 'p18',
        name: 'Scented Soy Candle Set',
        description: 'Hand-poured soy candles, 3 scents, 40hr burn each.',
        price: 29.99,
        originalPrice: 39.99,
        images: [
          'https://picsum.photos/seed/4760/600/800',
        ],
        category: 'Home & Living',
        rating: 4.7,
        reviewCount: 289,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 1500,
      ),
      ProductModel(
        id: 'p19',
        name: 'Macrame Wall Hanging',
        description: 'Handwoven bohemian wall decor, 100% cotton.',
        price: 39.99,
        images: [
          'https://picsum.photos/seed/1671/600/800',
        ],
        category: 'Home & Living',
        rating: 4.5,
        reviewCount: 123,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 450,
      ),
      ProductModel(
        id: 'p20',
        name: 'Ceramic Plant Pot Set',
        description: 'Matte ceramic planters with drainage, set of 3.',
        price: 24.99,
        originalPrice: 34.99,
        images: [
          'https://picsum.photos/seed/4437/600/800',
        ],
        category: 'Home & Living',
        rating: 4.6,
        reviewCount: 198,
        colors: ['White', 'Terracotta', 'Sage'],
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 890,
        isFlashSale: true,
        flashSalePrice: 15.99,
      ),
      ProductModel(
        id: 'p21',
        name: 'LED String Lights',
        description: 'Warm white, 10m, remote control, timer function.',
        price: 15.99,
        images: [
          'https://picsum.photos/seed/2403/600/800',
        ],
        category: 'Home & Living',
        rating: 4.4,
        reviewCount: 567,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 3400,
      ),
      ProductModel(
        id: 'p22',
        name: 'Velvet Throw Blanket',
        description: 'Luxurious soft velvet, 50x70 inches, machine washable.',
        price: 44.99,
        images: [
          'https://picsum.photos/seed/9980/600/800',
        ],
        category: 'Home & Living',
        rating: 4.8,
        reviewCount: 156,
        colors: ['Blush', 'Sage', 'Navy'],
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 670,
      ),
      ProductModel(
        id: 'p23',
        name: 'Minimalist Desk Lamp',
        description: 'Touch control, 3 brightness levels, USB charging.',
        price: 34.99,
        images: [
          'https://picsum.photos/seed/8370/600/800',
        ],
        category: 'Home & Living',
        rating: 4.5,
        reviewCount: 234,
        colors: ['Black', 'White', 'Wood'],
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 980,
      ),

      // ── BEAUTY ──
      ProductModel(
        id: 'p24',
        name: 'Vitamin C Serum',
        description: '20% Vitamin C, hyaluronic acid, brightening formula.',
        price: 24.99,
        originalPrice: 39.99,
        images: [
          'https://picsum.photos/seed/3293/600/800',
        ],
        category: 'Beauty',
        rating: 4.8,
        reviewCount: 890,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 4500,
        isFlashSale: true,
        flashSalePrice: 16.99,
      ),
      ProductModel(
        id: 'p25',
        name: 'Rose Water Toner',
        description: 'Organic rose water, alcohol-free, pH balancing.',
        price: 16.99,
        images: [
          'https://picsum.photos/seed/206/600/800',
        ],
        category: 'Beauty',
        rating: 4.6,
        reviewCount: 445,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 2300,
      ),
      ProductModel(
        id: 'p26',
        name: 'Retinol Night Cream',
        description: '0.5% retinol, peptides, anti-aging formula.',
        price: 34.99,
        originalPrice: 49.99,
        images: [
          'https://picsum.photos/seed/8721/600/800',
        ],
        category: 'Beauty',
        rating: 4.7,
        reviewCount: 321,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 1800,
      ),
      ProductModel(
        id: 'p27',
        name: 'Makeup Brush Set 12pc',
        description: 'Professional synthetic brushes with travel case.',
        price: 29.99,
        images: [
          'https://picsum.photos/seed/7326/600/800',
        ],
        category: 'Beauty',
        rating: 4.5,
        reviewCount: 678,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 3200,
      ),
      ProductModel(
        id: 'p28',
        name: 'Matte Lipstick Collection',
        description: 'Long-lasting, 6 shades, creamy matte finish.',
        price: 19.99,
        images: [
          'https://picsum.photos/seed/2782/600/800',
        ],
        category: 'Beauty',
        rating: 4.4,
        reviewCount: 234,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 1500,
      ),
      ProductModel(
        id: 'p29',
        name: 'Jade Roller & Gua Sha',
        description: 'Authentic jade stone, reduces puffiness.',
        price: 22.99,
        originalPrice: 32.99,
        images: [
          'https://picsum.photos/seed/1030/600/800',
        ],
        category: 'Beauty',
        rating: 4.3,
        reviewCount: 189,
        sellerId: 's5',
        sellerName: 'BeautyGlow',
        sellerAvatar: '✨',
        soldCount: 980,
      ),

      // ── SPORTS ──
      ProductModel(
        id: 'p30',
        name: 'Yoga Mat Premium',
        description: '6mm thick, non-slip, eco-friendly TPE material.',
        price: 34.99,
        originalPrice: 49.99,
        images: [
          'https://picsum.photos/seed/5046/600/800',
        ],
        category: 'Sports',
        rating: 4.6,
        reviewCount: 456,
        colors: ['Purple', 'Blue', 'Pink'],
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 2100,
      ),
      ProductModel(
        id: 'p31',
        name: 'Resistance Bands Set',
        description: '5 levels, fabric-covered, non-snap design.',
        price: 19.99,
        images: [
          'https://picsum.photos/seed/1571/600/800',
        ],
        category: 'Sports',
        rating: 4.5,
        reviewCount: 345,
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 1800,
      ),
      ProductModel(
        id: 'p32',
        name: 'Insulated Water Bottle',
        description: '32oz stainless steel, 24hr cold, 12hr hot.',
        price: 24.99,
        images: [
          'https://picsum.photos/seed/4088/600/800',
        ],
        category: 'Sports',
        rating: 4.7,
        reviewCount: 567,
        colors: ['Black', 'White', 'Green', 'Pink'],
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 3400,
        isFlashSale: true,
        flashSalePrice: 16.99,
      ),
      ProductModel(
        id: 'p33',
        name: 'Running Shoes Ultra',
        description: 'Lightweight mesh, responsive cushioning.',
        price: 89.99,
        originalPrice: 129.99,
        images: [
          'https://picsum.photos/seed/1463/600/800',
        ],
        category: 'Sports',
        rating: 4.8,
        reviewCount: 234,
        sizes: ['7', '8', '9', '10', '11'],
        colors: ['Black', 'Red', 'Blue'],
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 1200,
      ),
      ProductModel(
        id: 'p34',
        name: 'Gym Duffel Bag',
        description: '50L capacity, wet pocket, shoe compartment.',
        price: 39.99,
        images: [
          'https://picsum.photos/seed/3770/600/800',
        ],
        category: 'Sports',
        rating: 4.4,
        reviewCount: 178,
        colors: ['Black', 'Grey'],
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 670,
      ),

      // ── BOOKS ──
      ProductModel(
        id: 'p35',
        name: 'The Art of Mindfulness',
        description: 'Bestselling guide to meditation and inner peace.',
        price: 14.99,
        originalPrice: 22.99,
        images: [
          'https://picsum.photos/seed/2081/600/800',
        ],
        category: 'Books',
        rating: 4.8,
        reviewCount: 1234,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 5600,
      ),
      ProductModel(
        id: 'p36',
        name: 'Cookbook: World Flavors',
        description: '150 recipes from 30 countries, hardcover.',
        price: 29.99,
        images: [
          'https://picsum.photos/seed/1570/600/800',
        ],
        category: 'Books',
        rating: 4.6,
        reviewCount: 345,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 1200,
      ),
      ProductModel(
        id: 'p37',
        name: 'Science Fiction Collection',
        description: '5 award-winning sci-fi novels, box set.',
        price: 49.99,
        originalPrice: 74.99,
        images: [
          'https://picsum.photos/seed/9902/600/800',
        ],
        category: 'Books',
        rating: 4.7,
        reviewCount: 567,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 890,
      ),
      ProductModel(
        id: 'p38',
        name: "Children's Picture Book",
        description: 'Beautifully illustrated, ages 3-7, hardcover.',
        price: 12.99,
        images: [
          'https://picsum.photos/seed/3582/600/800',
        ],
        category: 'Books',
        rating: 4.9,
        reviewCount: 234,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 3400,
      ),

      // ── FOOD & DRINKS ──
      ProductModel(
        id: 'p39',
        name: 'Organic Green Tea Box',
        description: 'Premium Japanese sencha, 50 tea bags.',
        price: 12.99,
        originalPrice: 18.99,
        images: [
          'https://picsum.photos/seed/648/600/800',
        ],
        category: 'Food & Drinks',
        rating: 4.5,
        reviewCount: 456,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 2300,
      ),
      ProductModel(
        id: 'p40',
        name: 'Artisan Chocolate Box',
        description: 'Handcrafted Belgian chocolates, 24 pieces.',
        price: 34.99,
        images: [
          'https://picsum.photos/seed/9544/600/800',
        ],
        category: 'Food & Drinks',
        rating: 4.8,
        reviewCount: 345,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 1800,
        isFlashSale: true,
        flashSalePrice: 24.99,
      ),
      ProductModel(
        id: 'p41',
        name: 'Cold Brew Coffee Maker',
        description: '1.5L capacity, borosilicate glass, easy pour.',
        price: 27.99,
        images: [
          'https://picsum.photos/seed/7208/600/800',
        ],
        category: 'Food & Drinks',
        rating: 4.4,
        reviewCount: 234,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 980,
      ),
      ProductModel(
        id: 'p42',
        name: 'Protein Snack Box',
        description: '12-pack healthy snacks, gluten-free.',
        price: 22.99,
        originalPrice: 29.99,
        images: [
          'https://picsum.photos/seed/6330/600/800',
        ],
        category: 'Food & Drinks',
        rating: 4.3,
        reviewCount: 178,
        sellerId: 's6',
        sellerName: 'SportFlex',
        sellerAvatar: '⚽',
        soldCount: 1200,
      ),

      // ── TOYS & GAMES ──
      ProductModel(
        id: 'p43',
        name: 'Board Game Night Pack',
        description: '5 classic board games in one box.',
        price: 39.99,
        originalPrice: 59.99,
        images: [
          'https://picsum.photos/seed/5476/600/800',
        ],
        category: 'Toys & Games',
        rating: 4.7,
        reviewCount: 234,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 890,
      ),
      ProductModel(
        id: 'p44',
        name: 'Building Blocks 500pc',
        description: 'Compatible with major brands, creative set.',
        price: 29.99,
        images: [
          'https://picsum.photos/seed/5224/600/800',
        ],
        category: 'Toys & Games',
        rating: 4.6,
        reviewCount: 567,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 2300,
      ),
      ProductModel(
        id: 'p45',
        name: 'Plush Chicken Mascot',
        description: 'Official Tiny Chicken plush, 12 inches, super soft.',
        price: 19.99,
        images: [
          'https://picsum.photos/seed/1184/600/800',
        ],
        category: 'Toys & Games',
        rating: 4.9,
        reviewCount: 890,
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 4500,
        isFlashSale: true,
        flashSalePrice: 11.99,
      ),
      ProductModel(
        id: 'p46',
        name: 'RC Stunt Car',
        description: '360° flips, 30m range, rechargeable battery.',
        price: 34.99,
        images: [
          'https://picsum.photos/seed/9377/600/800',
        ],
        category: 'Toys & Games',
        rating: 4.3,
        reviewCount: 156,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 670,
      ),

      // ── AUTOMOTIVE ──
      ProductModel(
        id: 'p47',
        name: 'Car Phone Mount',
        description:
            'Magnetic, 360° rotation, dashboard/windshield compatible.',
        price: 15.99,
        images: [
          'https://picsum.photos/seed/7124/600/800',
        ],
        category: 'Automotive',
        rating: 4.4,
        reviewCount: 456,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 3400,
      ),
      ProductModel(
        id: 'p48',
        name: 'LED Interior Lights',
        description: 'App-controlled, 16M colors, music sync.',
        price: 19.99,
        originalPrice: 29.99,
        images: [
          'https://picsum.photos/seed/3897/600/800',
        ],
        category: 'Automotive',
        rating: 4.3,
        reviewCount: 345,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 2100,
      ),
      ProductModel(
        id: 'p49',
        name: 'Dash Cam 4K',
        description: 'Night vision, parking mode, 170° wide angle.',
        price: 79.99,
        images: [
          'https://picsum.photos/seed/8153/600/800',
        ],
        category: 'Automotive',
        rating: 4.6,
        reviewCount: 234,
        sellerId: 's3',
        sellerName: 'TechGear Hub',
        sellerAvatar: '🎧',
        soldCount: 890,
      ),

      // ── PETS ──
      ProductModel(
        id: 'p50',
        name: 'Orthopedic Dog Bed',
        description: 'Memory foam, removable washable cover.',
        price: 49.99,
        originalPrice: 69.99,
        images: [
          'https://picsum.photos/seed/4575/600/800',
        ],
        category: 'Pets',
        rating: 4.7,
        reviewCount: 345,
        sizes: ['S', 'M', 'L'],
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 1200,
      ),
      ProductModel(
        id: 'p51',
        name: 'Interactive Cat Toy',
        description: 'Automatic laser, rechargeable, 3 patterns.',
        price: 18.99,
        images: [
          'https://picsum.photos/seed/4414/600/800',
        ],
        category: 'Pets',
        rating: 4.5,
        reviewCount: 234,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 890,
      ),
      ProductModel(
        id: 'p52',
        name: 'Pet Grooming Kit',
        description: 'Professional clippers, 8 guide combs, quiet motor.',
        price: 39.99,
        images: [
          'https://picsum.photos/seed/4678/600/800',
        ],
        category: 'Pets',
        rating: 4.4,
        reviewCount: 178,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 670,
      ),
      ProductModel(
        id: 'p53',
        name: 'Stainless Steel Pet Bowl',
        description: 'Non-slip base, 2-pack, dishwasher safe.',
        price: 14.99,
        images: [
          'https://picsum.photos/seed/9738/600/800',
        ],
        category: 'Pets',
        rating: 4.6,
        reviewCount: 456,
        sellerId: 's4',
        sellerName: 'HomeStyle Living',
        sellerAvatar: '🏠',
        soldCount: 2300,
        isFlashSale: true,
        flashSalePrice: 8.99,
      ),

      // ── MORE FASHION ──
      ProductModel(
        id: 'p54',
        name: 'Silk Scarf Collection',
        description: '100% mulberry silk, hand-rolled edges.',
        price: 29.99,
        images: [
          'https://picsum.photos/seed/1778/600/800',
        ],
        category: 'Fashion',
        rating: 4.5,
        reviewCount: 123,
        colors: ['Red', 'Blue', 'Green'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 450,
      ),
      ProductModel(
        id: 'p55',
        name: 'Classic Aviator Sunglasses',
        description: 'UV400 protection, polarized, metal frame.',
        price: 24.99,
        images: [
          'https://picsum.photos/seed/8019/600/800',
        ],
        category: 'Fashion',
        rating: 4.4,
        reviewCount: 234,
        colors: ['Gold', 'Silver', 'Black'],
        sellerId: 's1',
        sellerName: 'Tiny Chicken Official',
        sellerAvatar: '🐔',
        soldCount: 1800,
      ),
    ];
  }

  static List<ProductModel> getFlashSaleProducts() =>
      getProducts().where((p) => p.isFlashSale).toList();
  static List<ProductModel> getFeaturedProducts() {
    final a = getProducts();
    return [a[0], a[10], a[17], a[23], a[32], a[44]];
  }

  static List<ProductModel> getNewArrivals() {
    final a = getProducts();
    return [a[1], a[12], a[19], a[29], a[35], a[42], a[50]];
  }

  static List<ProductModel> getTrendingProducts() {
    final a = getProducts();
    return [a[5], a[11], a[0], a[24], a[33], a[2]];
  }

  static List<ProductModel> getProductsBySeller(String id) =>
      getProducts().where((p) => p.sellerId == id).toList();
  static List<ProductModel> getProductsByCategory(String cat) =>
      getProducts().where((p) => p.category == cat).toList();
}
