// File generated by FlutterFire CLI.
// @dart = 2.12
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default Firebase configuration for Tiny Chicken.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyCWa0ISo1jIbS7ozxwqMbdTH4jh6Cb2T-M',
      appId: '1:924881312154:android:0df09440b733bfb4edc223',
      messagingSenderId: '924881312154',
      projectId: 'tiny-chicken',
      storageBucket: 'tiny-chicken.firebasestorage.app',
    );
  }
}
